DROP TABLE IF EXISTS compra_producto;
DROP TABLE IF EXISTS producto;
DROP TABLE IF EXISTS compra;
DROP TABLE IF EXISTS tarjeta;
DROP TABLE IF EXISTS titular;
DROP TABLE IF EXISTS estado_compra;
DROP TABLE IF EXISTS estado_tarjeta;
